name: Schedule

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  schedule:
    name: Schedule
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get node version
        id: node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - run: node --version

      - run: npm ci
      - run: npm run update-data
      - run: npm run build
      - run: npm test -- --ci --runInBand --coverage
      - run: npm run push-changes
