name: TypeDoc

on:
  - push

jobs:
  typedoc:
    name: TypeDoc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get node version
        id: node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
      - name: Node version
        run: node --version

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build-docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: docs
          clean: true
          dry-run: ${{ github.ref != 'refs/heads/main' }}
